### PR TITLE
Submit Transfer Learning Attack models and presentation

### PR DESCRIPTION
**Pull request by ESTA-2509**
I submit a presentation and all code files for Transfer Learning Attack models

### CODE REVIEW

**Review by sonnh-uit — CHANGES_REQUESTED** [review]
Xóa những file binary generate/download. Chỉ giữ các file code và text
- final/model-attack/ckpt/black-box/*.pt
- final/model-attack/data

**Comment by ESTA-2509** [comment]
I deleted all downloaded files at:
- final/model-attack/ckpt/black-box/*.pt
- final/model-attack/data

I also added new presentation file and merged from lastest

**Review by sonnh-uit — CHANGES_REQUESTED** [review]
Please refactor with structure
.
└── model-attack /
    ├── code/
    │   └── all code here
    └── slide # Must include all file on overleaf project, instead just only pdf file/
        ├── slide.tex
        ├── slide.pdf
        └── ...

**Review by ESTA-2509 — COMMENTED** [review]
I added latex source for slide and restructured model-attack folder

**Pull request merged**
